### ISSUE TITLE
Eliminate getdevihalf

### ISSUE THREAD

**Issue by ilario** [barnesgroupICL/Driftfusion#56]
While `getvarihalf` has to be used with care (avoid using on device property stuff, see discussion here below), `getdevihalf` usage is always a bad idea, in my opinion.

The reason is that `getdevihalf` is used for calculating what is already available in `par.dev_ihalf` BUT with different results in some cases:
`par.dev_ihalf` is generated via `build_device` and `build_property`, which for some variables use a logarithmic gradient in the junctions.
Contrariwise , `getdevihalf` always finds the value o the points in a linear way.
So the results are slightly different and this can result in different electrical fields calculated in `dfana.calcrho_ihalf`, for example.

I plotted an example of the NA profile on x_ihalf from Input_files/spiro_mapi_tio2.csv:

```
>> [u,t,x,par,dev,n,p,a,c,V] = dfana.splitsol(soleq.ion);
>> devihalf = getdevihalf(par)
>> plot(par.x_ihalf,devihalf.NA)
>> hold on
>> plot(par.x_ihalf,par.dev_ihalf.NA)
>> legend(["devihalf.NA","par.dev\_ihalf.NA"])
```

![Screenshot from 2020-05-26 12-11-41](https://user-images.githubusercontent.com/1329018/82889127-91c19280-9f4a-11ea-920b-020fb997ab17.png)

I suggested the removal of its usage in Core/dfana with #55.

Are you ok to completely remove the Core/getdevihalf.m file?

**Comment by barnesgroupICL** [comment]
This is really good detective work and obviously something I have completely neglected. Brilliant!
