### ISSUE TITLE
df/odeset/NonNegative is outdated and should be removed

### ISSUE THREAD

**Issue by ilario** [barnesgroupICL/Driftfusion#62]
The NonNegative option passed to the pdepe solver is set to `[1,1,1,0]`.

https://github.com/barnesgroupICL/Driftfusion/blob/09b3e67ff95273dfb89efe3e724452745f72cae5/Core/df.m#L142

This is not updated to the variables' order change and addition of a second ionic specie (from n,p,c,V to V,n,p,c,a).

As this did not cause any trouble, means that this option is being ignored and can be deleted. 

Indeed, the odeset help states: "NonNegative is not available for ode23s or ode15i. Additionally, for ode15s, ode23t, and ode23tb it is not available for problems where there is a mass matrix."

**Comment by barnesgroupICL** [comment]
Great thanks! It obviously does work as I have seen instances with negative densities for non-physical models.
