### ISSUE TITLE
Nani and Ncat disappeared from dfpde's S_V

### ISSUE THREAD

**Issue by ilario** [barnesgroupICL/Driftfusion#75]
In d581d02727920bce0e842c31882a2d1bb860af14 the Nani and Ncat terms disappeared from S_V (before that change it was `S_V = Field_switch(i)*(q/(eppmax*epp0))*(-n+p-NA(i)+ND(i)-a+c+Nani(i)-Ncat(i));` and after it became `S_V = Field_switch(i)*(q/(eppmax*epp0))*(-n+p-NA(i)+ND(i)-a+c);`), and looks like they could not simply be deleted without other changes.

Example of cases where it cause a malfunctioning:
* take an input file with 1 ionic specie and change the Nani value in every layer, the simulation will break while it should just ignore the Nani value;
* take an input file with 2 ionic species and set Nani to a value different from Ncat, the simulation will break.

**Comment by ilario** [comment]
Nani and Ncat have been reinstated in https://github.com/barnesgroupICL/Driftfusion/commit/a84c577d20ff69390367457516a16ebee5c22b7b but in order to allow the users to use a Nani value different from Ncat we still have to change this part of the code as it does not work for the `N_ions_species = 0`:
https://github.com/barnesgroupICL/Driftfusion/blob/8caea0da68cf949e4f5d523affcbef87e8d21c79/Core/df.m#L252-L255

A possible solution is simply to add the `case 0` in which also the `c = Ncat(i)` gets set.

This is the profiling of the first option (adding another `case` to the `switch`) when running an equilibrate on every input file (plus one input file with different Nani and Ncat) where the relevant lines are 254-256:

![Screenshot 2021-08-31 165056](https://user-images.githubusercontent.com/1329018/131525432-9e8f890a-fae4-41bd-9b8f-e712f5d3bcf4.png)

As a side note: notice how quick is the switch/case when it has to compare numerical values and how slow it is when it has to compare character arrays.

**Comment by barnesgroupICL** [comment]
I also realised this today and I'm currently testing the fixed version. I have chosen instead to set

`switch N_ionic_species
    case 0                  % Nani, Ncat, a, and c set to zero for Poisson
        Ncat = zeros(1, length(x_sub));
        Nani = zeros(1, length(x_sub));
    case 1                  % Nani and a both set to zero for Poisson
        Ncat = device.Ncat;
        Nani = zeros(1, length(x_sub));
    case 2
        Ncat = device.Ncat;
        Nani = device.Nani;
end`

at the start of df instead. This then means we can lose the switch for a = Nani(i) as both Nani and a are set to zero for the single ion case.

This approach has (curiously) increased the speed of equilibrate by up to 25% in some instances.

**Comment by ilario** [comment]
This is much better!
Amazing!

**Comment by barnesgroupICL** [comment]
Well it would be better to do this using a `set.` command in `pc` but the `dev` structures are not objects- when I experimented with making them objects things slowed down massively due to number of calls to `pc`. It was a long time ago however and this could be re-investigated at some stage. For the time being the above works well enough I think.
